# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-11 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('user', models.CharField(max_length=1024, verbose_name='用户')),
                ('device', models.CharField(default='', max_length=1024, verbose_name='设备名')),
                ('op', models.CharField(default='', max_length=1024, verbose_name='操作名')),
                ('info', models.TextField(verbose_name='操作信息')),
            ],
        ),
    ]
