# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-26 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='upload')),
                ('type', models.IntegerField(choices=[(0, '脸部'), (1, '舌头')], default=0, verbose_name='类型')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(default='', max_length=1024, verbose_name='设备名')),
                ('op', models.CharField(default='', max_length=1024, verbose_name='操作名')),
                ('info', models.TextField(blank=True, default='', verbose_name='操作信息')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tizhi', models.CharField(default='正常', max_length=16, verbose_name='体质')),
                ('score', models.IntegerField(verbose_name='分数')),
                ('tongue', models.CharField(max_length=2048, verbose_name='舌诊')),
                ('face', models.CharField(max_length=2048, verbose_name='面诊')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=48, verbose_name='用户名')),
                ('phone', models.CharField(max_length=16, verbose_name='用户手机号')),
                ('password', models.CharField(max_length=2048, verbose_name='用户密码')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CloudMedLog.User'),
        ),
        migrations.AddField(
            model_name='oplog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CloudMedLog.User'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CloudMedLog.User'),
        ),
    ]
